#! /bin/sh

sxhkd -r /user/monkinto/.config/sxhkd/sxhkdrc &
xrandr --output DP-0 --mode 1920x1080 --pos 0x420 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --mode 1920x1080 --pos 3840x0 --rotate left --output HDMI-0 --off --output DP-4 --primary --mode 1920x1080 --pos 1920x420 --rotate normal --output DP-5 --off &
launch-polybar.sh &
auto-launch.sh &

bspc monitor DP-0 -d 1 2 3
bspc monitor DP-4 -d 4 5 6 7 
bspc monitor DP-3 -d 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^8'
bspc rule -a Android Messages desktop='^8'
bspc rule -a Spotify desktop='^10'
